---
# tasks file for nginx_database

  - name: Install postgresql on database servers
    environment:
      DEBIAN_FRONTEND: noninteractive # like shut up 
    apt: 
      name: 
          - postgresql
          - postgresql-contrib
          - python3-psycopg2 # driver for Ansible
          - libpq-dev
          - sudo
      state: present
      update_cache: yes
    register: postgresql_install
    until: postgresql_install is success
    retries: 3
    delay: 5


  - name: Check registered variable
    debug:
      var: postgresql_install
  
  
  - name: Ensure postgresql is started
    service:
      name: postgresql
      state: started

  - name: Create database user
    become: true
    become_user: postgres # ansible ignoring become_user if become is not set to true 
    postgresql_user:
      name: "{{ db_user }}"
      password: "{{ db_user_password }}"