---
ansible_python_interpreter: /usr/bin/python3
ansible_connection: ssh
ansible_user: azureuser

ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

postgresql_admin_username: "{{lookup('env', 'TF_VAR_db_admin_username') }}"
postgresql_admin_password: "{{lookup('env', 'TF_VAR_db_admin_password') }}"

