---
# tasks file for nginx_database

  - name: Install PostgreSQL client libraries
    become: true
    apt: 
      name: 
        - python3-psycopg2 # necessary for postgresql_user 
        - libpq-dev
    state: present
    update_cache: yes

  - name: Login and create PostgreSQL user 

    community.postgresql.postgresql_user:
      login_host: "{{ postgresql_db_fqdn }}" # extra var from jenkins
      login_user: "{{ postgresql_admin_username }}" # from group_vars/all.yml
      login_password: "{{ postgresql_admin_password }}" # from group_vars/all.yml
      port: "{{ db_port }}" # from defaults/main.yml


      # create an new user
      name: "{{ postgresql_user_username }}" # vars/main.yml
      password: "{{ postgresql_user_password }}" # vault secrets.yaml
      state: present

      no_log: true # don't log the password in ansible output

