--- 

  - name: Setup backend servers
    hosts: role_web-server
    roles:
      - nginx_backend
    gather_facts: false 


  - name: Setup load balancer servers
    hosts: role_loadbalancer
    roles:
      - nginx_loadbalancer
    gather_facts: false

  - name: Setup database servers  
    # hosts: [prefix]_[tags.role]
    hosts: role_postgresql-database
    vars_files:
      - secrets.yml # we use vars from it
    roles:
      - nginx_database
    gather_facts: false
    