all:
  vars:
    ansible_connection: docker 
  children:
    app_servers:
      hosts:
        app-01:
        app-02:
    lb_servers:
      hosts:
        lb-01:
    db_servers:
      hosts:
        db-01:
